/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/insights': typeof AppInsightsRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/plan': typeof AppPlanRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/insights': typeof AppInsightsRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/plan': typeof AppPlanRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/pricing': typeof PricingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/pricing'
    | '/dashboard'
    | '/devices'
    | '/insights'
    | '/logs'
    | '/metrics'
    | '/plan'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/pricing'
    | '/dashboard'
    | '/devices'
    | '/insights'
    | '/logs'
    | '/metrics'
    | '/plan'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/blog'
    | '/pricing'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/insights'
    | '/_app/logs'
    | '/_app/metrics'
    | '/_app/plan'
    | '/_app/reports'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppPlanRoute: typeof AppPlanRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLogsRoute: AppLogsRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppPlanRoute: AppPlanRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
