/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiAdminScoreParityRouteImport } from './routes/api/admin/score-parity'
import { Route as ApiAdminBackfillScoresRouteImport } from './routes/api/admin/backfill-scores'
import { Route as ApiIntegrationsOuraSyncRouteImport } from './routes/api/integrations/oura/sync'
import { Route as ApiIntegrationsOuraCallbackRouteImport } from './routes/api/integrations/oura/callback'
import { Route as ApiIntegrationsOuraAuthorizeRouteImport } from './routes/api/integrations/oura/authorize'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScoreParityRoute = ApiAdminScoreParityRouteImport.update({
  id: '/api/admin/score-parity',
  path: '/api/admin/score-parity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBackfillScoresRoute = ApiAdminBackfillScoresRouteImport.update({
  id: '/api/admin/backfill-scores',
  path: '/api/admin/backfill-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsOuraSyncRoute = ApiIntegrationsOuraSyncRouteImport.update({
  id: '/api/integrations/oura/sync',
  path: '/api/integrations/oura/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsOuraCallbackRoute =
  ApiIntegrationsOuraCallbackRouteImport.update({
    id: '/api/integrations/oura/callback',
    path: '/api/integrations/oura/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsOuraAuthorizeRoute =
  ApiIntegrationsOuraAuthorizeRouteImport.update({
    id: '/api/integrations/oura/authorize',
    path: '/api/integrations/oura/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/insights': typeof AppInsightsRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/plan': typeof AppPlanRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/api/admin/backfill-scores': typeof ApiAdminBackfillScoresRoute
  '/api/admin/score-parity': typeof ApiAdminScoreParityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/integrations/oura/authorize': typeof ApiIntegrationsOuraAuthorizeRoute
  '/api/integrations/oura/callback': typeof ApiIntegrationsOuraCallbackRoute
  '/api/integrations/oura/sync': typeof ApiIntegrationsOuraSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/insights': typeof AppInsightsRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/plan': typeof AppPlanRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/api/admin/backfill-scores': typeof ApiAdminBackfillScoresRoute
  '/api/admin/score-parity': typeof ApiAdminScoreParityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/integrations/oura/authorize': typeof ApiIntegrationsOuraAuthorizeRoute
  '/api/integrations/oura/callback': typeof ApiIntegrationsOuraCallbackRoute
  '/api/integrations/oura/sync': typeof ApiIntegrationsOuraSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/admin/backfill-scores': typeof ApiAdminBackfillScoresRoute
  '/api/admin/score-parity': typeof ApiAdminScoreParityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/integrations/oura/authorize': typeof ApiIntegrationsOuraAuthorizeRoute
  '/api/integrations/oura/callback': typeof ApiIntegrationsOuraCallbackRoute
  '/api/integrations/oura/sync': typeof ApiIntegrationsOuraSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/dashboard'
    | '/devices'
    | '/insights'
    | '/logs'
    | '/metrics'
    | '/plan'
    | '/reports'
    | '/settings'
    | '/api/admin/backfill-scores'
    | '/api/admin/score-parity'
    | '/api/public/health'
    | '/api/integrations/oura/authorize'
    | '/api/integrations/oura/callback'
    | '/api/integrations/oura/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/dashboard'
    | '/devices'
    | '/insights'
    | '/logs'
    | '/metrics'
    | '/plan'
    | '/reports'
    | '/settings'
    | '/api/admin/backfill-scores'
    | '/api/admin/score-parity'
    | '/api/public/health'
    | '/api/integrations/oura/authorize'
    | '/api/integrations/oura/callback'
    | '/api/integrations/oura/sync'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/blog'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/insights'
    | '/_app/logs'
    | '/_app/metrics'
    | '/_app/plan'
    | '/_app/reports'
    | '/_app/settings'
    | '/api/admin/backfill-scores'
    | '/api/admin/score-parity'
    | '/api/public/health'
    | '/api/integrations/oura/authorize'
    | '/api/integrations/oura/callback'
    | '/api/integrations/oura/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAdminBackfillScoresRoute: typeof ApiAdminBackfillScoresRoute
  ApiAdminScoreParityRoute: typeof ApiAdminScoreParityRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiIntegrationsOuraAuthorizeRoute: typeof ApiIntegrationsOuraAuthorizeRoute
  ApiIntegrationsOuraCallbackRoute: typeof ApiIntegrationsOuraCallbackRoute
  ApiIntegrationsOuraSyncRoute: typeof ApiIntegrationsOuraSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/score-parity': {
      id: '/api/admin/score-parity'
      path: '/api/admin/score-parity'
      fullPath: '/api/admin/score-parity'
      preLoaderRoute: typeof ApiAdminScoreParityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/backfill-scores': {
      id: '/api/admin/backfill-scores'
      path: '/api/admin/backfill-scores'
      fullPath: '/api/admin/backfill-scores'
      preLoaderRoute: typeof ApiAdminBackfillScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/oura/sync': {
      id: '/api/integrations/oura/sync'
      path: '/api/integrations/oura/sync'
      fullPath: '/api/integrations/oura/sync'
      preLoaderRoute: typeof ApiIntegrationsOuraSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/oura/callback': {
      id: '/api/integrations/oura/callback'
      path: '/api/integrations/oura/callback'
      fullPath: '/api/integrations/oura/callback'
      preLoaderRoute: typeof ApiIntegrationsOuraCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/oura/authorize': {
      id: '/api/integrations/oura/authorize'
      path: '/api/integrations/oura/authorize'
      fullPath: '/api/integrations/oura/authorize'
      preLoaderRoute: typeof ApiIntegrationsOuraAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppPlanRoute: typeof AppPlanRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLogsRoute: AppLogsRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppPlanRoute: AppPlanRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAdminBackfillScoresRoute: ApiAdminBackfillScoresRoute,
  ApiAdminScoreParityRoute: ApiAdminScoreParityRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiIntegrationsOuraAuthorizeRoute: ApiIntegrationsOuraAuthorizeRoute,
  ApiIntegrationsOuraCallbackRoute: ApiIntegrationsOuraCallbackRoute,
  ApiIntegrationsOuraSyncRoute: ApiIntegrationsOuraSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
